[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = app3M_fat9M_16MB.csv
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
monitor_speed = 115200
lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git
    olikraus/U8g2
    bblanchon/ArduinoJson
build_flags = -DBOARD_HAS_PSRAM -DCORE_DEBUG_LEVEL=0
